apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ofddb"
  namespace: "default"
  labels:
    app: "ofddb"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "ofddb"
  template:
    metadata:
      labels:
        app: "ofddb"
    spec:
      containers:
      - name: "ofddatabase-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/jyothipedakotla499/ofddatabase@sha256:54570a1cf278bf948704810057fb2d0cb4a27604d633d3f70cc022bbbd749ec1"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ofddb-hpa-dev6"
  namespace: "default"
  labels:
    app: "ofddb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ofddb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
